import Bond from "../models/bond";

export default [
    new Bond("I owe my life to the priest who took me in when my parents died."),
    new Bond("Everything I do is for the common people."),
    new Bond("I will do anything to protect my local temple."),
    new Bond("I would die to recover an ancient relic of my faith that was lost long ago."),
    new Bond("I’m trying to pay off an old debt I owe to a generous benefactor."),
    new Bond("My ill-gotten gains go to support my family."),
    new Bond("Something important was taken from me, and I aim to steal it back."),
    new Bond("I’m guilty of a terrible crime. I hope I can redeem myself for it."),
    new Bond("Someone I loved died because of a mistake I made. That will never happen again."),
    new Bond("I have a family, but I have no idea where they are. One day, I hope to see them again."),
    new Bond("A proud noble once gave me a horrible beating, and I will take my revenge on any bully I encounter."),
    new Bond("I hope to be able to protect my village one day."),
    new Bond("My tools are the symbols of my life."),
    new Bond("I hope to be able protect those who cannot protect themselves.."),
    new Bond("I wish my childhood sweetheart had come with me to pursue my destiny."),
    new Bond("I keep my thoughts and discoveries in a journal. Maybe someone will remember me."),
    new Bond("My torment drove away the person I love. I strive to win back the love I’ve lost."),
    new Bond("I will stand up for the innocent"),
    new Bond("A terrible guilt consumes me. I hope that I can find redemption through my actions."),
    new Bond("There’s evil in me, I can feel it. It must never be set free."),
    new Bond("I have a child to protect my child at all costs."),
    new Bond("I will face any challenge to win the approval of my family."),
    new Bond("Nothing is more important than the other members of my family."),
    new Bond("I am in love with a member of a family that my family despises."),
    new Bond("My loyalty to my sovereign is unwavering."),
    new Bond("I will be seen as a hero one day."),
    new Bond("It is my duty to protect my apprentices."),
    new Bond("I have an ancient text that holds terrible secrets that must not fall into the wrong hands."),
    new Bond("I’ve been searching my whole life for the answer to a certain question."),
    new Bond("I want to sell my soul for knowledge."),
    new Bond("I would still lay down my life for the people I served with."),
    new Bond("Someone saved my life on the battlefield. To this day, I will never leave a friend behind."),
    new Bond("My honor is my life."),
    new Bond("I will fight to protect this village."),
    new Bond("I will always be there for those who have been there for me."),
];
