import Flaw from "../models/flaw";

export default [
  new Flaw("I judge others harshly, and myself even more severely."),
    new Flaw("I put too much trust in religious leaders."),
    new Flaw("My piety sometimes leads me to blindly trust those that profess faith in my god."),
    new Flaw("I am inflexible in my thinking."),
    new Flaw("I am suspicious of strangers and expect the worst of them."),
    new Flaw("Once I pick a goal, I become obsessed with it to the detriment of everything else in my life."),
    new Flaw("When I see something valuable, I can’t think about anything but how to steal it."),
    new Flaw("When faced with a choice between money and my friends, I usually choose the money."),
    new Flaw("If there’s a plan, I’ll forget it. If I don’t forget it, I’ll ignore it."),
    new Flaw("I have a “tell” that reveals when I’m lying."),
    new Flaw("I turn tail and run when things look bad."),
    new Flaw("An innocent person is in prison for a crime that I committed. I’m okay with that."),
    new Flaw("The tyrant who rules my land will stop at nothing to ruin my life."),
    new Flaw("I’m convinced of the significance of my destiny, and blind to my shortcomings and the risk of failure."),
    new Flaw("The people who knew me when I was young know my shameful secret, so I can never go home again."),
    new Flaw("I have a weakness for the vices of the city, especially hard drink."),
    new Flaw("Secretly, I believe that things would be better if I were a tyrant lording over the land."),
    new Flaw("I have trouble trusting in my allies."),
    new Flaw("I have certain rituals that I must follow every day. I can never break them."),
    new Flaw("I assume the worst in people."),
    new Flaw("I feel no compassion for the dead. They’re the lucky ones."),
    new Flaw("I have an addiction."),
    new Flaw("I am a purveyor of doom and gloom who lives in a world without hope."),
    new Flaw("I talk to spirits that no one else can see."),
    new Flaw("I secretly believe that everyone is beneath me."),
    new Flaw("I hide a truly scandalous secret that could ruin my family forever."),
    new Flaw("I too often hear veiled insults and threats in every word addressed to me, and I’m quick to anger."),
    new Flaw("I have an insatiable desire for carnal pleasures."),
    new Flaw("In fact, the world does revolve around me."),
    new Flaw("By my words and actions, I often bring shame to my family."),
    new Flaw("I am easily distracted by the promise of information."),
    new Flaw("Most people scream and run when they see a demon. I stop and take notes on its anatomy."),
    new Flaw("I overlook obvious solutions in favor of complicated ones."),
    new Flaw("I speak without really thinking through my words, invariably insulting others."),
    new Flaw("I can’t keep a secret to save my life, or anyone else’s."),
    new Flaw("The monstrous enemy we faced in battle still leaves me quivering with fear."),
    new Flaw("I have little respect for anyone who is not a proven warrior."),
    new Flaw("I made a terrible mistake in battle that cost many lives—and I would do anything to keep that mistake secret."),
    new Flaw("My hatred of my enemies is blind and unreasoning."),
    new Flaw("I obey the law, even if the law causes misery."),
    new Flaw("I’d rather eat my shoe than admit when I’m wrong."),
];
