import Ideal from "../models/ideal";

export default [
    new Ideal("Tradition. The ancient traditions of worship and sacrifice must be preserved and upheld. (Lawful)"),
    new Ideal("Charity. I always try to help those in need, no matter what the personal cost. (Good)"),
    new Ideal("Change. We must help bring about the changes the gods are constantly working in the world. (Chaotic)"),
    new Ideal("Faith. I trust that my deity will guide my actions. I have faith that if I work hard, things will go well. (Lawful)"),
    new Ideal("Aspiration. I seek to prove myself worthy of my god’s favor by matching my actions against his or her teachings. (Any)"),
    new Ideal("Honor. I don’t steal from others in the trade. (Lawful)"),
    new Ideal("Freedom. Chains are meant to be broken, as are those who would forge them. (Chaotic)"),
    new Ideal("Charity. I will try and scam what I can from the wealthy so that I can help people in need. (Good)"),
    new Ideal("Greed. I will do whatever it takes to become wealthy. (Evil)"),
    new Ideal("People. I’m loyal to my friends, not to any ideals, and everyone else can take a trip down the Styx for all I care. (Neutral)"),
    new Ideal("Redemption. There’s a spark of good in everyone. (Good)"),
    new Ideal("Respect. People deserve to be treated with dignity and respect. (Good)"),
    new Ideal("Fairness. No one should get preferential treatment before the law, and no one is above the law. (Lawful)"),
    new Ideal("Freedom. Tyrants must not be allowed to oppress the people. (Chaotic)"),
    new Ideal("Might. If I become strong, I can take what I want—what I deserve. (Evil)"),
    new Ideal("Sincerity. There’s no good in pretending to be something I’m not. (Neutral)"),
    new Ideal("Destiny. Nothing and no one can steer me away from my higher calling. (Any)"),
    new Ideal("I try to help those in need, no matter what the personal cost. (Good)"),
    new Ideal("I’ll stop the spirits that haunt me or die trying. (Any)"),
    new Ideal("Killing monsters will make the world a safer place, and exorcise my demons. (Good)"),
    new Ideal("I feel a dark calling that will put me above the law. (Chaotic)"),
    new Ideal("Respect. All people regardless of station deserve to be treated with dignity. (Good)"),
    new Ideal("Power. If I can attain more power, no one will tell me what to do. (Evil)"),
    new Ideal("Family. Blood runs thicker than water. (Any)"),
    new Ideal("Knowledge. The path to power and self-improvement is through knowledge. (Neutral)"),
    new Ideal("Beauty. What is beautiful points us beyond itself toward what is true. (Good)"),
    new Ideal("Logic. Emotions must not cloud our logical thinking. (Lawful)"),
    new Ideal("No Limits. Nothing should fetter the infinite possibility inherent in all existence. (Chaotic)"),
    new Ideal("Power. Knowledge is the path to power and domination. (Evil)"),
    new Ideal("Self-Improvement. The goal of a life of study is the betterment of oneself. (Any)"),
    new Ideal("Greater Good. Our lot is to lay down our lives in defense of others. (Good)"),
    new Ideal("Responsibility. I do what I must and obey just authority. (Lawful)"),
    new Ideal("Independence. When people follow orders blindly, they embrace a kind of tyranny. (Chaotic)"),
    new Ideal("Might. In life as in war, the stronger force wins. (Evil)"),
    new Ideal("Live and Let Live. Ideals aren’t worth killing over or going to war for. (Neutral)\t"),
    new Ideal("Nation. My city, nation, or people are all that matter. (Any)")
];
