import PersonalityTrait from "../models/personalityTrait";

export default [
    new PersonalityTrait("I idolize a particular hero of my faith, and constantly refer to that person’s deeds and example."),
    new PersonalityTrait("I see omens in every event and action. The gods try to speak to us, we just need to listen."),
    new PersonalityTrait("Nothing can shake my optimistic attitude."),
    new PersonalityTrait("I quote (or misquote) sacred texts and proverbs in almost every situation."),
    new PersonalityTrait("I am tolerant (or intolerant) of other faiths and respect (or condemn) the worship of other gods."),
    new PersonalityTrait("I always have a plan for what to do when things go wrong."),
    new PersonalityTrait("I am always calm, no matter what the situation. I never raise my voice or let my emotions control me."),
    new PersonalityTrait("The first thing I do in a new place is note the locations of everything valuable—or where such things could be hidden."),
    new PersonalityTrait("I would rather make a new friend than a new enemy."),
    new PersonalityTrait("I am incredibly slow to trust. Those who seem the fairest often have the most to hide."),
    new PersonalityTrait("The best way to get me to do something is to tell me I can’t do it."),
    new PersonalityTrait("I blow up at the slightest insult."),
    new PersonalityTrait("I spend money freely and live life to the fullest, knowing that tomorrow I might die."),
    new PersonalityTrait("I judge people by their actions, not their words."),
    new PersonalityTrait("If someone is in trouble, I’m always ready to lend help."),
    new PersonalityTrait("When I set my mind to something, I follow through no matter what gets in my way."),
    new PersonalityTrait("I have a strong sense of fair play and always try to find the most equitable solution to arguments."),
    new PersonalityTrait("I’m confident in my own abilities and do what I can to instill confidence in others."),
    new PersonalityTrait("Thinking is for other people. I prefer action."),
    new PersonalityTrait("I misuse long words in an attempt to sound smarter."),
    new PersonalityTrait("I get bored easily. When am I going to get on with my destiny?"),
    new PersonalityTrait("I refuse to become a victim, and I will not allow others to be victimized."),
    new PersonalityTrait("I like to read and memorize poetry. It keeps me calm and brings me fleeting moments of happiness."),
    new PersonalityTrait("I put no trust in divine beings."),
    new PersonalityTrait("I expect to find trouble everywhere."),
    new PersonalityTrait("I hate those who bully others."),
    new PersonalityTrait("I spend money freely and live life to the fullest, who knows what tomorrow may bring?"),
    new PersonalityTrait("My eloquent flattery makes everyone I talk to feel like the most wonderful and important person in the world."),
    new PersonalityTrait("Everyone loves me for my kindness and generosity."),
    new PersonalityTrait("I take great pains to always look my best and follow the latest fashions."),
    new PersonalityTrait("Cross me and you will pay."),
    new PersonalityTrait("I use polysyllabic words that convey the impression of great erudition."),
    new PersonalityTrait("I am very well read —or, at least, I like to boast that I am."),
    new PersonalityTrait("I’m willing to listen to every side of an argument before I make my own judgment."),
    new PersonalityTrait("I … speak … slowly … when talking … to idiots, … which … almost … everyone … is … compared … to me."),
    new PersonalityTrait("I am horribly, horribly awkward in social situations."),
    new PersonalityTrait("I’m convinced that people are always trying to steal my secrets."),
    new PersonalityTrait("I’m used to helping out those who aren’t as smart as I am, and I patiently explain anything and everything to others."),
    new PersonalityTrait("I’m always polite and respectful."),
    new PersonalityTrait("I’m haunted by memories of war. I can’t get the images of violence out of my mind."),
    new PersonalityTrait("I’ve lost too many friends, and I’m slow to make new ones."),
    new PersonalityTrait("I enjoy being strong and like breaking things."),
    new PersonalityTrait("Nothing frightens me."),
    new PersonalityTrait("I have a crude sense of humor."),
    new PersonalityTrait("I’m always polite and respectful."),
    new PersonalityTrait("I face problems head-on. A simple, direct solution is the best path to success."),
]
