import Personality from "../models/personality";

export default [
    new Personality("I idolize a particular hero of my faith, and constantly refer to that person’s deeds and example."),
    new Personality("I see omens in every event and action. The gods try to speak to us, we just need to listen."),
    new Personality("Nothing can shake my optimistic attitude."),
    new Personality("I quote (or misquote) sacred texts and proverbs in almost every situation."),
    new Personality("I am tolerant (or intolerant) of other faiths and respect (or condemn) the worship of other gods."),
    new Personality("I always have a plan for what to do when things go wrong."),
    new Personality("I am always calm, no matter what the situation. I never raise my voice or let my emotions control me."),
    new Personality("The first thing I do in a new place is note the locations of everything valuable—or where such things could be hidden."),
    new Personality("I would rather make a new friend than a new enemy."),
    new Personality("I am incredibly slow to trust. Those who seem the fairest often have the most to hide."),
    new Personality("The best way to get me to do something is to tell me I can’t do it."),
    new Personality("I blow up at the slightest insult."),
    new Personality("I spend money freely and live life to the fullest, knowing that tomorrow I might die."),
    new Personality("I judge people by their actions, not their words."),
    new Personality("If someone is in trouble, I’m always ready to lend help."),
    new Personality("When I set my mind to something, I follow through no matter what gets in my way."),
    new Personality("I have a strong sense of fair play and always try to find the most equitable solution to arguments."),
    new Personality("I’m confident in my own abilities and do what I can to instill confidence in others."),
    new Personality("Thinking is for other people. I prefer action."),
    new Personality("I misuse long words in an attempt to sound smarter."),
    new Personality("I get bored easily. When am I going to get on with my destiny?"),
    new Personality("I refuse to become a victim, and I will not allow others to be victimized."),
    new Personality("I like to read and memorize poetry. It keeps me calm and brings me fleeting moments of happiness."),
    new Personality("I put no trust in divine beings."),
    new Personality("I expect to find trouble everywhere."),
    new Personality("I hate those who bully others."),
    new Personality("I spend money freely and live life to the fullest, who knows what tomorrow may bring?"),
    new Personality("My eloquent flattery makes everyone I talk to feel like the most wonderful and important person in the world."),
    new Personality("Everyone loves me for my kindness and generosity."),
    new Personality("I take great pains to always look my best and follow the latest fashions."),
    new Personality("Cross me and you will pay."),
    new Personality("I use polysyllabic words that convey the impression of great erudition."),
    new Personality("I am very well read —or, at least, I like to boast that I am."),
    new Personality("I’m willing to listen to every side of an argument before I make my own judgment."),
    new Personality("I … speak … slowly … when talking … to idiots, … which … almost … everyone … is … compared … to me."),
    new Personality("I am horribly, horribly awkward in social situations."),
    new Personality("I’m convinced that people are always trying to steal my secrets."),
    new Personality("I’m used to helping out those who aren’t as smart as I am, and I patiently explain anything and everything to others."),
    new Personality("I’m always polite and respectful."),
    new Personality("I’m haunted by memories of war. I can’t get the images of violence out of my mind."),
    new Personality("I’ve lost too many friends, and I’m slow to make new ones."),
    new Personality("I enjoy being strong and like breaking things."),
    new Personality("Nothing frightens me."),
    new Personality("I have a crude sense of humor."),
    new Personality("I’m always polite and respectful."),
    new Personality("I face problems head-on. A simple, direct solution is the best path to success."),
    new Personality("I lie, cheat, and steal at every opportunity."),
    new Personality("I use humor to hide my real emotions."),
    new Personality("I do not like losing...ever."),
    new Personality("I find joy in the little things in life."),
    new Personality("I enjoy the comforts of my daily routine, change bothers me."),
]
