import Proficiency from "../models/proficiency";

export const SmithsTools = new Proficiency(0, "Smith's Tools");
export const SleightOfHand = new Proficiency(1, "Sleight of Hand");
export const ConSavingThrows = new Proficiency(2, "Con. Saving Throws");
export const Investigation = new Proficiency(3, "Investigation");
export const Medicine = new Proficiency(4, "Medicine");
export const Perception = new Proficiency(5, "Perception");
export const Persuasion = new Proficiency(5, "Persuasion");
export const AnimalHandling = new Proficiency(6, "Animal Handling");
export const Intimidation = new Proficiency(6, "Intimidation");
export const Religion = new Proficiency(7, "Religion");
export const Lute = new Proficiency(8, "Lute");
export const StrengthSavingThrows = new Proficiency(9, "Strength Saving Throws");
export const Stealth = new Proficiency(10, "Stealth");
export const LeatherWorkersToolsProf = new Proficiency(11, "Leatherworker's Tools");
export const Arcana = new Proficiency(12, 'Arcana');
export const History = new Proficiency(13, 'History');
export const CharismaSavingThrows = new Proficiency(14, "Charisma Saving Throws");
export const HeavyArmor = new Proficiency(15, "Heavy Armor");
export const Nature = new Proficiency(16, "Nature");
export const Acrobatics = new Proficiency(17, "Acrobatics");
export const GlassblowersTools = new Proficiency(18, "Glassblower's Tools");
export const SailingShip = new Proficiency(19, "Sailing Ship");
export const TinkersTools = new Proficiency(20, "Tinker's Tools");
export const Deception = new Proficiency(21, "Deception");
